# To get started with Dependabot, see the documentation:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for npm (JavaScript/TypeScript dependencies)
  - package-ecosystem: "npm" # Locates package.json and pnpm-lock.yaml
    directory: "/" # Location of your package.json
    schedule:
      interval: "weekly" # How often to check for updates (e.g., "daily", "weekly", "monthly")
      day: "monday" # Specify a day to run on (e.g., "monday", "saturday")
      time: "09:00" # Specify a time to run at (HH:MM)
      timezone: "Asia/Yangon" # Use your current timezone
    open-pull-requests-limit: 10 # Limit the number of open PRs to avoid too much noise
    reviewers:
      - your-github-username # Replace with your GitHub username or your team's
    labels:
      - "dependencies"
      - "dependabot"
    # Optional: Group minor and patch updates for less PR noise
    groups:
      sveltekit-dependencies:
        patterns:
          - "@sveltejs/*"
          - "svelte"
          - "vite"
          - "typescript"
          - "eslint*"
          - "prettier*"
        update-types:
          - "minor"
          - "patch"

  # Configuration for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your workflow files (e.g., .github/workflows)
    schedule:
      interval: "weekly" # Check for updates to GitHub Actions every week
      day: "monday"
      time: "09:00"
      timezone: "Asia/Yangon"
    open-pull-requests-limit: 5
    reviewers:
      - your-github-username # Replace with your GitHub username or your team's
    labels:
      - "dependencies"
      - "github-actions"