name: SvelteKit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or 'macos-latest', 'windows-latest' if preferred

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Match this with the Node.js version in your devcontainer.json
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint # Assumes you have a 'lint' script in your package.json, e.g., "lint": "prettier --check . && eslint ."

      - name: Run Build
        run: pnpm build # Assumes you have a 'build' script in your package.json


      # Optional: Uncomment and configure if you have tests
      # - name: Run Tests
      #   run: pnpm test # Assumes you have a 'test' script in your package.json, e.g., "test": "vitest run"
