name: SvelteKit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm' # Keep this for caching node_modules and pnpm store

      # --- START OF CHANGE ---
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # Use the dedicated pnpm setup action
        with:
          version: 9 # Specify a major version, e.g., 8, 9, or 'latest'
          run_install: false # We'll run pnpm install in a separate step explicitly

      # --- END OF CHANGE ---

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint

      - name: Run Build
        run: pnpm build

      # Optional: Uncomment and configure if you have tests
      # - name: Run Tests
      #   run: pnpm test
